version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "127.0.0.1:3302:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24  # Choose a unique one for each project
