version: "3.8"

services:
  web:
    container_name: hr-inventory-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://hr-inventory-be.final25.psewmad.org
    ports:
      - "3302:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: https://hr-inventory-be.final25.psewmad.org
