# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: inventory-frontend
#     ports:
#       - "127.0.0.1:3302:3000"
#     restart: always
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

  nginx:
    image: nginx:alpine
    ports:
      - "3302:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
