version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "127.0.0.1:3302:3000"
    environment:
      - NODE_ENV=production
    restart: always