import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarItem } from "./components/sidebarItem";
import {
  Search,
  Bell,
  Package,
  Store,
  PackageX,
  Layers,
  Truck,
} from "lucide-react";
import Navbar from "./components/navbar";
import Link from "next/link";
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
/>


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="flex h-[760px]">
          {/* Sidebar on the left */}
          <div className="w-96 bg-[#2D579A] text-white text-[20px]">
            <nav className="mt-6">
              <SidebarItem
                icon={<Package size={25} />}
                text="Dashboard"
                href="/dashboard"
              />
              <SidebarItem
                icon={<Store size={25} />}
                text="Suppliers"
                href="/suppliers"
              />
              <SidebarItem
                icon={<Layers size={25} />}
                text="Category"
                href="/category"
              />
              <SidebarItem
                icon={<Package size={25} />}
                text="Product"
                href="/product"
              />
              <SidebarItem
                icon={<Package size={25} />}
                text="Stock In"
                href="/stock-in"
              />
              <SidebarItem
                icon={<PackageX size={25} />}
                text="Stock Out"
                href="/stock-out"
              />
              <SidebarItem
                icon={<Package size={25} />}
                text="Create User"
                href="/create-user"
              />
            </nav>
          </div>

          {/* Main content on the right */}
          <main className="flex-1 bg-gray-50 p-6 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
